[global]
type=global
user_agent=KPI Voice Helpdesk PBX

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=__KPI_PBX_PUBLIC_IP__
external_signaling_address=__KPI_PBX_PUBLIC_IP__

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0:8088

[7001]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
allow=alaw
auth=7001-auth
aors=7001
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
media_use_received_transport=yes

[7001-auth]
type=auth
auth_type=userpass
username=7001
password=KpiPhone7001!

[7001]
type=aor
max_contacts=1
remove_existing=yes

[7002]
type=endpoint
transport=transport-ws
context=from-internal
disallow=all
allow=opus
allow=ulaw
allow=alaw
auth=7002-auth
aors=7002
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
webrtc=yes

[7002-auth]
type=auth
auth_type=userpass
username=7002
password=KpiWebPhone7002!

[7002]
type=aor
max_contacts=1
remove_existing=yes
